import = ["~/.config/alacritty/colors.toml"]

[window]
padding = { x = 8, y = 8 }
opacity = 0.8

[font]
normal = { family = "FantasqueSansM Nerd Font" }
size = 12

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "Paste" }
]
