[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"
bright_foreground = "#ffffff"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "#44475a"
background = "#50fa7b"

[colors.search.focused_match]
foreground = "#44475a"
background = "#ffb86c"

[colors.hints.start]
foreground = "#282a36"
background = "#f1fa8c"

[colors.hints.end]
foreground = "#f1fa8c"
background = "#282a36"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
background = "#282a36"
foreground = "#f8f8f2"

[colors.selection]
text = "CellForeground"
background = "#44475a"

[colors.normal]
black = "#21222c"
red = "#a8324c"
green = "#21b58b"
yellow = "#ffb30f"
blue = "#63549e"
magenta = "#fe64a3"
cyan = "#5da5cf"
white = "#f8f8f2"

[colors.bright]
black = "#6272a4"
red = "#a8324c"
green = "#21b58b"
yellow = "#ffb30f"
blue = "#63549e"
magenta = "#fe64a3"
cyan = "#5da5cf"
white = "#ffffff"
